name: Merge Changelog

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - master
  merge_group:

jobs:
  merge:
    if: github.event_name != 'pull_request' && github.event.pull_request.head.ref == 'changelog-deb'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge PR
        run: gh pr merge ${{ github.event.pull_request.number }} --rebase --delete-branch --admin
        env:
          GITHUB_TOKEN: ${{ github.token }}
