name: Merge Changelog

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - master

jobs:
  merge:
    if: github.head_ref != 'changelog-deb'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge PR
        run: gh pr merge ${{ github.event.pull_request.number }} --rebase --delete-branch --admin
        env:
          GITHUB_TOKEN: ${{ github.token }}
