name: RUn Go Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4' # 根据需要指定Go版本

      - name: Run go test
        run: go test github.com/SongZihuan/TestGithubAction

  test-centeos:
    runs-on: ubuntu-latest
    container:
      image: centos:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4' # 根据需要指定Go版本

      - name: Run go test
        run: go test github.com/SongZihuan/TestGithubAction
