name: Run Go Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.ref != 'changelog-deb'
    runs-on: ubuntu-latest

    steps:
      - name: Start Run Test
        run: echo "start run test"

  test-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest

    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4' # 根据需要指定Go版本

      - name: Run go test
        run: go test github.com/SongZihuan/TestGithubAction

  test-redhat:
    runs-on: ubuntu-latest
    container:
      image: redhat/ubi9

    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4' # 根据需要指定Go版本

      - name: Run go test
        run: go test github.com/SongZihuan/TestGithubAction
