name: Go Test

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4' # 根据需要指定Go版本

      - name: Run go test
        run: go test github.com/SongZihuan/TestGithubAction

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4' # 根据需要指定Go版本

      - name: Build go
        run: go build -o "$GITHUB_WORKSPACE/huan-go-test" github.com/SongZihuan/TestGithubAction

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: huan-go-test
          path: "$GITHUB_WORKSPACE/huan-go-test"
  run:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: huan-go-test
          path: "$GITHUB_WORKSPACE/huan-go-test"

      - name: List Work Directory
        run: ls -l

      - name: Run huan-go-test
        run: "$GITHUB_WORKSPACE/huan-go-test"

  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, world!"
